version : "2.1"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /home/${USER}/jarloc/db:/data/db
    ports:
        - 27017:27017
    networks:
       - microservicesnet      
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  activemq:
    image: webcenter/activemq:latest
    container_name: "activemq"
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    networks:
      - microservicesnet  
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - /home/${USER}/jarloc/activemq/data:/data/activemq
      - /home/${USER}/jarloc/activemq/log:/var/log/activemq

    
  producer:
    image: hiteshjoshi1/microservice-docker-cart-example
    container_name: producer
    ports:
     - "3333:3333"
    networks:
      - microservicesnet
    volumes:
      - /home/${USER}/jarloc:/data
    command: -jar -Dspring.profiles.active=docker  /data/producer-0.0.1-SNAPSHOT.jar
    depends_on:
      mongodb:
         condition: service_started
      activemq:  
          condition: service_started

  consumer:
    image: hiteshjoshi1/microservice-docker-cart-example
    container_name: consumer
    ports:
     - "4444:4444"
    networks:
      - microservicesnet
    volumes:
      - /home/${USER}/jarloc:/data
    command: -jar -Dspring.profiles.active=docker /data/consumer-0.0.1-SNAPSHOT.jar
    depends_on:
       mongodb:
         condition: service_started
       activemq:  
          condition: service_started
networks:
  microservicesnet:
