#notice the use of profiles one for localhost, one for docker
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off" 
  http:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  activemq:
    in-memory: false
    user: admin
    password: admin      
  data:
    mongodb:
      database: imageDB  
    
logging:
  file: application.log

server:
  port: ${port:3333} 

activemq:
    image:
       queue: consensys-image-queue 
        
user: 
  pdfFolderName: PDFFolder
  imageFolderName : ImageFolder
  finalPDFName : final.pdf




---

spring:
  profiles: dev
  activemq:
    broker-url: tcp://localhost:61616
  data:
    mongodb:
      uri: mongodb://localhost:27017
user: 
  baseDir: C:\\Users\\hitjoshi     
    
---

spring:
  profiles: docker
  activemq:
    broker-url: tcp://activemq:61616
  data:
    mongodb:
      uri: mongodb://mongodb:27017   
user: 
  baseDir: /home/joshi/datadir     

    
    